-- ### Text fonts

-- DESCRIPTION:
-- Fallback icons that will be displayed
-- if you don't have nerd fonts installed,
-- or if you set `vim.g.icons_enabled = false` on `../1-options.lua`.

return {
  ActiveLSP = "LSP:",
  ArrowLeft = "<",
  ArrowRight = ">",
  BufferClose = "x",
  DapBreakpoint = "B",
  DapBreakpointCondition = "C",
  DapBreakpointRejected = "R",
  DapLogPoint = "L",
  DapStopped = ">",
  DefaultFile = "[F]",
  DiagnosticError = "X",
  DiagnosticHint = "?",
  DiagnosticInfo = "i",
  DiagnosticWarn = "!",
  Ellipsis = "...",
  Environment = "Env:",
  FileModified = "*",
  FileReadOnly = "[lock]",
  FoldClosed = "+",
  FoldOpened = "-",
  FoldSeparator = " ",
  FolderClosed = "[D]",
  FolderEmpty = "[E]",
  FolderOpen = "[O]",
  GitAdd = "[+]",
  GitChange = "[/]",
  GitConflict = "[!]",
  GitDelete = "[-]",
  GitIgnored = "[I]",
  GitRenamed = "[R]",
  GitStaged = "[S]",
  GitUnstaged = "[U]",
  GitUntracked = "[?]",
  MacroRecording = "Recording:",
  Paste = "[PASTE]",
  Search = "?",
  Selected = "*",
  Spellcheck = "[SPELL]",
  TabClose = "X",
}
